"""
Presidio-based text synthesizer for generating synthetic clinical text.

Uses Microsoft Presidio to detect PII entities in template text and replaces
them with realistic synthetic alternatives generated by Faker.
"""

from faker import Faker
from presidio_analyzer import AnalyzerEngine
from presidio_analyzer.nlp_engine import NlpEngineProvider
from presidio_anonymizer import AnonymizerEngine
from presidio_anonymizer.entities import OperatorConfig


def _build_nlp_engine(model_name: str = "en_core_web_sm"):
    """Build a spaCy NLP engine for Presidio using the specified model."""
    provider = NlpEngineProvider(
        nlp_configuration={
            "nlp_engine_name": "spacy",
            "models": [{"lang_code": "en", "model_name": model_name}],
        }
    )
    return provider.create_engine()


class PresidioSynthesizer:
    """
    Synthesizes clinical text by detecting PII with Presidio and replacing
    each entity with a realistic Faker-generated alternative.

    Example
    -------
    >>> synth = PresidioSynthesizer()
    >>> note = "Patient Jane Doe, DOB 1972-05-10, SSN 123-45-6789."
    >>> print(synth.synthesize(note))
    Patient <synthetic name>, DOB <synthetic date>, SSN <synthetic ssn>.
    """

    def __init__(self, locale: str = "en_US", spacy_model: str = "en_core_web_sm"):
        self.fake = Faker(locale)
        nlp_engine = _build_nlp_engine(spacy_model)
        self.analyzer = AnalyzerEngine(nlp_engine=nlp_engine)
        self.anonymizer = AnonymizerEngine()
        self._operators = self._build_operators()

    def _build_operators(self) -> dict:
        """Return a mapping of Presidio entity type -> Faker OperatorConfig."""
        fake = self.fake
        return {
            "PERSON": OperatorConfig(
                "custom", {"lambda": lambda x: fake.name()}
            ),
            "PHONE_NUMBER": OperatorConfig(
                "custom", {"lambda": lambda x: fake.phone_number()}
            ),
            "EMAIL_ADDRESS": OperatorConfig(
                "custom", {"lambda": lambda x: fake.email()}
            ),
            "US_SSN": OperatorConfig(
                "custom", {"lambda": lambda x: fake.ssn()}
            ),
            "DATE_TIME": OperatorConfig(
                "custom",
                {"lambda": lambda x: fake.date(pattern="%Y-%m-%d")},
            ),
            "LOCATION": OperatorConfig(
                "custom", {"lambda": lambda x: fake.city()}
            ),
            "ORGANIZATION": OperatorConfig(
                "custom", {"lambda": lambda x: fake.company()}
            ),
            "CREDIT_CARD": OperatorConfig(
                "custom", {"lambda": lambda x: fake.credit_card_number()}
            ),
            "IP_ADDRESS": OperatorConfig(
                "custom", {"lambda": lambda x: fake.ipv4()}
            ),
            "URL": OperatorConfig(
                "custom", {"lambda": lambda x: fake.url()}
            ),
            "NRP": OperatorConfig(
                "custom", {"lambda": lambda x: fake.country()}
            ),
        }

    def synthesize(self, text: str) -> str:
        """
        Detect PII in *text* using Presidio Analyzer and replace each
        entity with a Faker-generated synthetic value.

        Parameters
        ----------
        text:
            Input text that may contain PII.

        Returns
        -------
        str
            Text with all detected PII replaced by synthetic equivalents.
        """
        results = self.analyzer.analyze(text=text, language="en")
        if not results:
            return text
        anonymized = self.anonymizer.anonymize(
            text=text,
            analyzer_results=results,
            operators=self._operators,
        )
        return anonymized.text
